const ACTION_TYPES = {
    FETCH_GOALS_SUCCESS: 'FETCH_GOALS_SUCCESS',
    TOGGLE_CREATE_GOAL_MODAL: 'TOGGLE_CREATE_GOAL_MODAL',
    SAVE_GOAL_SUCCESS: 'SAVE_GOAL_SUCCESS'
};

export default ACTION_TYPES;